# Generated by Django 5.1.2 on 2025-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="user_user_usernam_6d9439_idx"),
        ),
    ]
